version: '3.8'

services:
  web:
    image: nginx:alpine
    ports:
      - "8081:80"
    volumes:
      - ./magento:/var/www/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - mysql
    networks:
      - magento-network

  php:
    image: php:8.1-fpm
    volumes:
      - ./magento:/var/www/html
      - ./php.ini:/usr/local/etc/php/conf.d/custom.ini
    environment:
      - PHP_MEMORY_LIMIT=2G
    networks:
      - magento-network

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: magento
      MYSQL_DATABASE: magento
      MYSQL_USER: magento
      MYSQL_PASSWORD: magento
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - magento-network

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    networks:
      - magento-network

  elasticsearch:
    image: elasticsearch:7.17.0
    environment:
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ports:
      - "9200:9200"
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data
    networks:
      - magento-network

volumes:
  mysql_data:
  elasticsearch_data:

networks:
  magento-network:
    driver: bridge 