<?php
/**
 * Taxcloud_Magento2
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 *
 * @package    Taxcloud_Magento2
 * @author     TaxCloud <service@taxcloud.net>
 * @copyright  2025 The Federal Tax Authority, LLC d/b/a TaxCloud
 * @license    http://opensource.org/licenses/osl-3.0.php Open Software License (OSL 3.0)
 */

/** @var \Taxcloud\Magento2\Block\Adminhtml\System\Config\TicField $block */
/** @var \Magento\Framework\Escaper $escaper */

$element = $block->getElement();
$uid = $element ? $element->getHtmlId() : 'taxcloud_tic';
?>
<div data-bind="scope: '<?= $escaper->escapeHtmlAttr($uid) ?>'">
    <!-- ko template: getTemplate() --><!-- /ko -->
</div>
<script type="text/x-magento-init">
    <?= /* @noEscape */ $block->getComponentJson() ?>
</script>
