name: 'Deploy Module to Server'
description: 'Deploy TaxCloud Magento2 module to a Magento installation via SFTP'
inputs:
  server:
    description: 'Server hostname or IP'
    required: true
  username:
    description: 'SSH username'
    required: true
  ssh-key:
    description: 'SSH private key'
    required: true
  port:
    description: 'SSH port'
    required: false
    default: '22'
  magento-root:
    description: 'Magento root directory path'
    required: true
  module-path:
    description: 'Module path relative to Magento root'
    required: true
  web-user:
    description: 'Web server user'
    required: true
  web-group:
    description: 'Web server group'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Create deployment package
      shell: bash
      run: |
        # Create a clean deployment package
        mkdir -p deployment-package
        
        # Copy specific files and directories needed for deployment
        cp -r Model/ deployment-package/
        cp -r Observer/ deployment-package/
        cp -r Logger/ deployment-package/
        cp -r Setup/ deployment-package/
        cp -r etc/ deployment-package/
        cp registration.php deployment-package/
        cp composer.json deployment-package/
        
        # Create deployment archive
        cd deployment-package
        tar -czf ../taxcloud-magento2-deployment.tar.gz .
        cd ..
        
    - name: Deploy via SCP
      uses: appleboy/scp-action@v0.1.7
      with:
        host: ${{ inputs.server }}
        username: ${{ inputs.username }}
        key: ${{ inputs.ssh-key }}
        port: ${{ inputs.port }}
        source: './deployment-package/*'
        target: '${{ inputs.magento-root }}/${{ inputs.module-path }}/'
          
    - name: Execute Magento Commands
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ inputs.server }}
        username: ${{ inputs.username }}
        key: ${{ inputs.ssh-key }}
        port: ${{ inputs.port }}
        script: |
          cd ${{ inputs.magento-root }}
          
          # Set proper permissions
          chmod -R 755 ${{ inputs.module-path }}
          chown -R ${{ inputs.web-user }}:${{ inputs.web-group }} ${{ inputs.module-path }}
          
          # Enable module if not already enabled
          bin/magento module:enable Taxcloud_Magento2
          
          # Run Magento setup commands
          bin/magento setup:upgrade
          bin/magento setup:di:compile
          bin/magento setup:static-content:deploy -f
          bin/magento cache:clean
          bin/magento cache:flush
          
          # Verify module is enabled
          bin/magento module:status Taxcloud_Magento2
